AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 99

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize: 
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/ParameterLists:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $redis